import Head from 'next/head';

// import { EThemeTag } from '@/components/Tag/interface';
// import Tag from '@/components/Tag';

import Main from './Main';
import Career from './Career';
import Project from './Project';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* 메인 */}
      <Main />
      {/* 경력 */}
      <Career />
      {/* 프로젝트 */}
      <Project />
    </>
  );
}
